### ISSUE TITLE
Summary/status for fast track February 2019

### ISSUE THREAD

**Issue by LuisaIckes** [wmo-im/wmds#78]
The following still needs to be done:

 - [x] [Issue 53](https://github.com/wmo-im/wmds/issues/53) Table 2-02, DBCP affiliation -> needs still input how this should be done in the end
 - [x] [Issue 44](https://github.com/wmo-im/wmds/issues/44) Table 1-01-01, new entries -> needs agreement on what should be added and what not
 - [x] [Issue 17](https://github.com/wmo-im/wmds/issues/17) Table 1-02, new variables -> one question open about the description of some of the new variables, eventually more new variables from Markus?
-  [x] [Issue 5](https://github.com/wmo-im/wmds/issues/5) read me -> needs some input what should be included in the read me
 - [x] [Issue 77](https://github.com/wmo-im/wmds/issues/77) Consistent naming for columns
 - [x] [Issue 74](https://github.com/wmo-im/wmds/issues/74) Remove extra columns
 - [x] [Issue 80](https://github.com/wmo-im/wmds/issues/80) Correction of paths
 - [x] [Issue 81](https://github.com/wmo-im/wmds/issues/81) Table 1-04, 10-01 column status
